// Selector options configuration - extensible data source
const SELECTOR_OPTIONS = {
  photo: {
    device: [
      "iPhone",
      "Canon",
      "Sony",
      "Nikon",
      "Fujifilm",
      "Samsung Galaxy",
      "Google Pixel",
      "Leica",
      "Hasselblad",
      "Polaroid",
      "Instant Camera",
      "GoPro",
      "DJI Drone",
      "Medium Format"
    ],
    lens_type: [
      "Fisheye",
      "14mm",
      "24mm",
      "35mm",
      "50mm",
      "85mm",
      "100mm",
      "135mm",
      "200mm",
      "300mm"
    ],
    custom: [
      "HDR",
      "Long Exposure",
      "Panorama",
      "Time-lapse",
      "Double Exposure",
      "High Speed",
      "Macro",
      "Tilt-Shift",
      "Infrared",
      "Shallow DOF"
    ]
  },
  art: {
    style: [
      "Oil Painting",
      "Watercolor",
      "Digital Art",
      "Anime",
      "Manga",
      "Comic Book",
      "Realistic",
      "Abstract",
      "Impressionist",
      "Expressionist",
      "Surrealist",
      "Pop Art",
      "Cubism",
      "Art Nouveau",
      "Art Deco",
      "Baroque",
      "Gothic",
      "Ukiyo-e",
      "Minimalist",
      "Concept Art",
      "Storybook",
      "Sketch",
      "Line Art",
      "Ink Wash",
      "Pointillism",
      "Stippling"
    ],
    colors: [
      "Vibrant",
      "Pastel",
      "Monochrome",
      "Warm Tones",
      "Cool Tones",
      "Earth Tones",
      "Neon",
      "Muted",
      "High Contrast",
      "Duotone",
      "Sepia"
    ],
    medium: [
      "Pencil",
      "Charcoal",
      "Ink",
      "Pastel Crayon",
      "Acrylic",
      "Oil",
      "Gouache",
      "Spray Paint",
      "Canvas",
      "Paper",
      "Digital Tablet",
      "Mixed Media",
      "Collage",
      "Woodblock"
    ]
  },
  render: {
    style: [
      "3D Render",
      "Pixar",
      "Disney",
      "Pixel Art",
      "Cel Shading",
      "Low Poly",
      "Isometric",
      "Voxel Art",
      "Claymation",
      "Paper Craft",
      "LEGO Style",
      "Wireframe",
      "Retro 3D"
    ],
    quality: [
      "Photorealistic",
      "Stylized",
      "Hyper-realistic",
      "Painterly",
      "Cartoon",
      "Chibi",
      "Semi-realistic"
    ],
    engine: [
      "Blender",
      "Maya",
      "Cinema 4D",
      "Houdini",
      "ZBrush",
      "Substance Painter",
      "Unreal Engine 5",
      "Unity"
    ]
  },
  design: {
    type: [
      "Graphic Design",
      "Logo",
      "Poster",
      "Flyer",
      "Book Cover",
      "Album Cover",
      "Magazine Layout",
      "Packaging",
      "Label",
      "Business Card",
      "UI / App Screen",
      "Website Layout",
      "Icon Set",
      "Infographic",
      "Typography Art",
      "Motion Graphics",
      "Sticker",
      "T-shirt Design",
      "Tattoo Design",
      "Pattern / Textile"
    ],
    aesthetic: [
      "Modern",
      "Minimalist",
      "Retro",
      "Vintage",
      "Swiss / International",
      "Bauhaus",
      "Memphis",
      "Y2K",
      "Brutalist",
      "Maximalist",
      "Vaporwave",
      "Cyberpunk",
      "Art Deco",
      "Psychedelic",
      "Corporate",
      "Organic",
      "Geometric",
      "Hand Drawn",
      "Flat Design",
      "Glassmorphism",
      "Neomorphism"
    ],
    reference: {
      "Graphic Design": ["Saul Bass", "Paul Rand", "Massimo Vignelli", "Milton Glaser", "Paula Scher", "David Carson", "Stefan Sagmeister", "Josef Müller-Brockmann", "Herb Lubalin", "Neville Brody", "Shepard Fairey", "Pentagram"],
      "Logo": ["Paul Rand", "Milton Glaser", "Paula Scher", "Saul Bass", "Massimo Vignelli", "Pentagram", "Nike", "Apple", "NASA", "Supreme"],
      "Poster": ["Saul Bass", "Milton Glaser", "Paula Scher", "Shepard Fairey", "David Carson", "Josef Müller-Brockmann", "Neville Brody", "Vogue", "Pentagram"],
      "Flyer": ["Shepard Fairey", "David Carson", "Milton Glaser", "Neville Brody", "Supreme", "Pentagram"],
      "Book Cover": ["Chip Kidd", "David Carson", "Paula Scher", "Massimo Vignelli", "Muji", "Pentagram"],
      "Album Cover": ["Stefan Sagmeister", "David Carson", "Milton Glaser", "Saul Bass", "Neville Brody", "KAWS", "Takashi Murakami"],
      "Magazine Layout": ["Vogue", "David Carson", "Massimo Vignelli", "Herb Lubalin", "Neville Brody", "Pentagram"],
      "Packaging": ["Dieter Rams", "Apple", "Muji", "Paul Rand", "Supreme", "Pentagram", "Nike"],
      "Label": ["Milton Glaser", "Muji", "Supreme", "Pentagram", "Vogue"],
      "Business Card": ["Massimo Vignelli", "Josef Müller-Brockmann", "Muji", "Apple", "Pentagram"],
      "UI / App Screen": ["Apple", "Dieter Rams", "Muji", "Pentagram"],
      "Website Layout": ["Apple", "Massimo Vignelli", "Josef Müller-Brockmann", "Muji", "Pentagram"],
      "Icon Set": ["Apple", "Dieter Rams", "NASA", "Muji", "Pentagram"],
      "Infographic": ["Massimo Vignelli", "Josef Müller-Brockmann", "NASA", "Pentagram"],
      "Typography Art": ["Herb Lubalin", "Paula Scher", "David Carson", "Massimo Vignelli", "Neville Brody", "Josef Müller-Brockmann"],
      "Motion Graphics": ["Saul Bass", "Apple", "Neville Brody", "Pentagram"],
      "Sticker": ["Shepard Fairey", "KAWS", "Takashi Murakami", "Supreme", "Nike", "NASA"],
      "T-shirt Design": ["Supreme", "Nike", "Shepard Fairey", "KAWS", "Takashi Murakami", "Apple"],
      "Tattoo Design": ["Takashi Murakami", "KAWS", "Shepard Fairey"],
      "Pattern / Textile": ["Takashi Murakami", "Muji", "Supreme", "Nike", "KAWS", "Vogue"]
    }
  },
  view: {
    perspective: [
      "Front",
      "Back",
      "Side",
      "High Angle",
      "Low Angle",
      "Bird's Eye",
      "Worm's Eye",
      "Three-quarter",
      "Over-the-shoulder",
      "Dutch Angle",
      "POV / First Person"
    ],
    distance: [
      "Wide",
      "Medium",
      "Close-up",
      "Extreme Close-up",
      "Full Body",
      "Cowboy Shot",
      "Bust Shot",
      "Portrait",
      "Establishing Shot"
    ]
  },
  subject: {
    characteristic: [
      "Young",
      "Old",
      "Athletic",
      "Slim",
      "Muscular",
      "Elegant",
      "Casual",
      "Professional",
      "Adventurous",
      "Mysterious",
      "Cute",
      "Fierce"
    ],
    clothes: [
      "Formal",
      "Casual",
      "Traditional",
      "Futuristic",
      "Fantasy",
      "Business",
      "Athletic",
      "Vintage",
      "Streetwear",
      "Military",
      "Gothic",
      "Elegant"
    ],
    action: [
      "Standing",
      "Sitting",
      "Walking",
      "Running",
      "Dancing",
      "Fighting",
      "Reading",
      "Working",
      "Relaxing",
      "Sleeping",
      "Flying",
      "Swimming",
      "Driving",
      "Cooking",
      "Playing Instrument",
      "Singing",
      "Interacting",
      "Meditating",
      "Posing",
      "Crouching",
      "Leaping"
    ],
    top_type: [
      "T-shirt",
      "Shirt",
      "Blouse",
      "Crop top",
      "Tank top",
      "Sweater",
      "Hoodie",
      "Jacket",
      "Coat",
      "Robe",
      "Dress",
      "Bra",
      "Bralette",
      "Bikini Top",
      "Sports Bra",
      "Corset",
      "Armor",
      "Kimono",
      "Vest",
      "Cape"
    ],
    bottom_type: [
      "Jeans",
      "Pants",
      "Skirt",
      "Shorts",
      "Leggings",
      "Panties",
      "Underwear",
      "Bikini Bottom",
      "Fishnet Stockings",
      "Armor",
      "Cargo Pants",
      "Sweatpants"
    ],
    accessories: [
      "Glasses",
      "Sunglasses",
      "Hat",
      "Scarf",
      "Jewelry",
      "Watch",
      "Gloves",
      "Belt",
      "Hand Bag",
      "Backpack",
      "Shoulder Bag",
      "Headphones",
      "Mask",
      "Veil",
      "Chains",
      "Choker",
      "Necklace",
      "Bracelet",
      "Ring",
      "Earrings",
      "Crown",
      "Tiara",
      "Tattoo",
      "Piercing",
      "Cape"
    ],
    weapon: [
      "Sword",
      "Katana",
      "Axe",
      "Gun",
      "Bow",
      "Crossbow",
      "Staff",
      "Dagger",
      "Spear",
      "Hammer",
      "Magic Wand",
      "Nunchucks",
      "Glaive",
      "Flail",
      "Scythe",
      "Shield",
      "Dual Blades",
      "Trident"
    ],
    hair_color: [
      "Black",
      "Brown",
      "Blonde",
      "Red",
      "White",
      "Gray",
      "Pink",
      "Blue",
      "Purple",
      "Green",
      "Auburn",
      "Strawberry Blonde",
      "Silver",
      "Ombre",
      "Multicolor"
    ],
    hair_style: [
      "Short",
      "Long",
      "Curly",
      "Straight",
      "Wavy",
      "Ponytail",
      "Twin Tails",
      "Bun",
      "Braids",
      "Dreadlocks",
      "Buzz Cut",
      "Undercut",
      "Afro",
      "Mohawk",
      "Bob Cut",
      "Pixie Cut",
      "Side Swept",
      "Bald"
    ]
  },
  scene: {
    scene_1: [
      "Indoor",
      "Bedroom",
      "Living Room",
      "Kitchen",
      "Bathroom",
      "Studio",
      "Office",
      "Cafe",
      "Outdoor",
      "Beach",
      "Desert",
      "Forest",
      "Mountain",
      "City",
      "Alley",
      "Rooftop",
      "Nature",
      "Garden",
      "Temple",
      "Castle",
      "Dungeon",
      "Ruins",
      "Fantasy World",
      "Cyberpunk",
      "Historical",
      "Sci-Fi",
      "Post-Apocalyptic",
      "Underwater",
      "Space"
    ],
    scene_2: [
      "Day",
      "Night",
      "Dusk",
      "Sunset",
      "Sunrise",
      "Overcast",
      "Rainy",
      "Snowy",
      "Foggy",
      "Stormy",
      "Windy",
      "Misty",
      "Clear Sky"
    ],
    effect: [
      "Lens Flare",
      "Analog Grain",
      "Light Leak",
      "Bokeh",
      "Motion Blur",
      "Radial Blur",
      "Chromatic Aberration",
      "Vignette",
      "Prism Effect",
      "Double Vision",
      "Film Damage",
      "Dust Particles",
      "Rain Droplets",
      "Snow Particles",
      "Glitch",
      "Smoke / Haze"
    ],
    photo_filter: [
      "Film Simulation",
      "Instagram filter",
      "Tiktok effect",
      "Tiktok sticker",
      "B&W Classic",
      "B&W High Contrast",
      "Cyanotype",
      "Cross Process",
      "Lomography",
      "Kodachrome"
    ]
  },
  lighting: {
    lighting_1: [
      "Natural",
      "Studio",
      "Golden Hour",
      "Blue Hour",
      "Night City Lights",
      "Neon",
      "Cinematic",
      "Soft",
      "Hard",
      "Rembrandt",
      "Butterfly",
      "Candlelight",
      "Moonlight",
      "Fluorescent",
      "LED"
    ],
    lighting_2: [
      "Front Lit",
      "Back Lit",
      "Side Lit",
      "Rim Light",
      "Dramatic",
      "Flat",
      "High Contrast",
      "Low Key",
      "High Key",
      "Film Noir",
      "Silhouette",
      "Split Lighting",
      "Volumetric"
    ]
  }
};

// Randomization presets — exclude illogical combos per subject type
const RANDOM_PRESETS = {
  none: { label: "No Filter", exclude: {} },
  woman: {
    label: "Woman",
    exclude: {
      'subject-hair-style': ['Bald', 'Buzz Cut'],
      'subject-weapon': ['Hammer', 'Axe', 'Flail', 'Nunchucks'],
    }
  },
  man: {
    label: "Man",
    exclude: {
      'subject-top-type': ['Bra', 'Bralette', 'Bikini Top', 'Sports Bra', 'Corset', 'Crop top', 'Dress'],
      'subject-bottom-type': ['Panties', 'Bikini Bottom', 'Fishnet Stockings', 'Skirt'],
      'subject-hair-style': ['Ponytail', 'Twin Tails', 'Bun', 'Braids', 'Pixie Cut'],
      'subject-clothes': ['Elegant'],
      'subject-accessory': ['Tiara', 'Veil'],
    }
  },
  child: {
    label: "Child",
    exclude: {
      'subject-top-type': ['Bra', 'Bralette', 'Bikini Top', 'Sports Bra', 'Corset', 'Crop top'],
      'subject-bottom-type': ['Panties', 'Bikini Bottom', 'Fishnet Stockings'],
      'subject-characteristic': ['Old', 'Muscular', 'Professional', 'Mysterious', 'Fierce'],
      'subject-weapon': ['Gun', 'Axe', 'Hammer', 'Flail', 'Nunchucks', 'Crossbow', 'Scythe'],
      'subject-clothes': ['Business', 'Formal', 'Gothic', 'Military'],
      'subject-accessory': ['Choker', 'Veil', 'Chains', 'Tattoo', 'Piercing'],
    }
  },
  fantasy: {
    label: "Fantasy",
    exclude: {
      'photo-device': ['iPhone', 'Samsung Galaxy', 'Google Pixel', 'GoPro', 'DJI Drone'],
      'scene-photo-filter': ['Instagram filter', 'Tiktok effect', 'Tiktok sticker'],
    }
  },
  modern: {
    label: "Modern",
    exclude: {
      'subject-clothes': ['Traditional', 'Futuristic', 'Fantasy', 'Vintage'],
      'subject-top-type': ['Armor', 'Kimono'],
      'subject-bottom-type': ['Armor'],
      'subject-weapon': ['Sword', 'Katana', 'Axe', 'Bow', 'Crossbow', 'Staff', 'Dagger', 'Spear', 'Hammer', 'Magic Wand', 'Glaive', 'Flail', 'Scythe', 'Shield', 'Dual Blades', 'Trident'],
      'subject-accessory': ['Crown', 'Tiara', 'Cape'],
      'scene-1': ['Temple', 'Castle', 'Dungeon', 'Ruins', 'Fantasy World', 'Historical', 'Sci-Fi']
    }
  },
  scifi: {
    label: "Sci-Fi",
    exclude: {
      'subject-clothes': ['Traditional', 'Fantasy', 'Vintage'],
      'subject-top-type': ['Kimono', 'Armor'],
      'subject-bottom-type': ['Armor'],
      'subject-weapon': ['Sword', 'Katana', 'Axe', 'Bow', 'Crossbow', 'Staff', 'Dagger', 'Spear', 'Hammer', 'Glaive', 'Flail', 'Scythe', 'Shield', 'Dual Blades', 'Trident'],
      'scene-1': ['Castle', 'Dungeon', 'Ruins', 'Historical', 'Fantasy World'],
      'scene-photo-filter': ['Cyanotype', 'Cross Process', 'Lomography', 'Kodachrome']
    }
  },
  historical: {
    label: "Historical / Vintage",
    exclude: {
      'photo-device': ['iPhone', 'Samsung Galaxy', 'Google Pixel', 'GoPro', 'DJI Drone'],
      'subject-clothes': ['Futuristic', 'Streetwear', 'Athletic'],
      'subject-accessory': ['Headphones'],
      'subject-weapon': ['Gun'],
      'scene-1': ['Cyberpunk', 'Sci-Fi', 'Post-Apocalyptic', 'Space', 'Office'],
      'scene-photo-filter': ['Instagram filter', 'Tiktok effect', 'Tiktok sticker']
    }
  },
  casual: {
    label: "Casual / Everyday",
    exclude: {
      'subject-clothes': ['Fantasy', 'Futuristic', 'Military', 'Gothic'],
      'subject-top-type': ['Armor', 'Kimono', 'Cape'],
      'subject-bottom-type': ['Armor'],
      'subject-weapon': ['Sword', 'Katana', 'Axe', 'Gun', 'Bow', 'Crossbow', 'Staff', 'Dagger', 'Spear', 'Hammer', 'Magic Wand', 'Nunchucks', 'Glaive', 'Flail', 'Scythe', 'Shield', 'Dual Blades', 'Trident'],
      'subject-accessory': ['Crown', 'Tiara', 'Cape', 'Chains', 'Veil'],
      'scene-1': ['Dungeon', 'Castle', 'Ruins', 'Fantasy World', 'Space', 'Underwater', 'Desert'],
      'subject-action': ['Fighting', 'Flying', 'Leaping']
    }
  },
  cyberpunk: {
    label: "Cyberpunk",
    exclude: {
      'subject-clothes': ['Traditional', 'Formal', 'Vintage', 'Business'],
      'subject-accessory': ['Tiara', 'Crown', 'Veil'],
      'scene-1': ['Nature', 'Forest', 'Castle', 'Dungeon', 'Garden', 'Historical'],
      'art-colors': ['Pastel', 'Earth Tones', 'Muted']
    }
  }
};
