// Selector options configuration - extensible data source
const SELECTOR_OPTIONS = {
  photo: {
    device: [
      "iPhone",
      "Canon",
      "Sony",
      "Nikon",
      "Fujifilm",
      "Samsung Galaxy",
      "Google Pixel",
      "Leica",
      "Hasselblad",
      "Polaroid",
      "Instant Camera",
      "None"
    ],
    lens_type: [
      "Fisheye",
      "24mm",
      "35mm",
      "50mm",
      "85mm",
      "100mm",
      "200mm",
      "None"
    ],
    custom: [
      "HDR",
      "Long Exposure",
      "Panorama",
      "Time-lapse",
      "Double Exposure",
      "High Speed",
      "Macro",
      "Tilt-Shift",
      "None"
    ]
  },
  painting_drawing: {
    style: [
      "Oil Painting",
      "Watercolor",
      "Digital Art",
      "Anime",
      "Realistic",
      "Abstract",
      "Impressionist",
      "Surrealist",
      "Pop Art",
      "Cubism",
      "Art Nouveau",
      "Minimalist"
    ],
    colors: [
      "Vibrant",
      "Pastel",
      "Monochrome",
      "Warm Tones",
      "Cool Tones",
      "Earth Tones",
      "Neon",
      "Muted",
      "High Contrast"
    ],
    custom: [
      "Mixed Media",
      "Collage",
      "Sketch",
      "Line Art",
      "Pointillism",
      "Stippling",
      "None"
    ]
  },
  view: {
    perspective: [
      "Front",
      "Back",
      "Side",
      "High Angle",
      "Low Angle",
      "Bird's Eye",
      "Worm's Eye",
      "Three-quarter",
      "Over-the-shoulder"
    ],
    distance: [
      "Wide",
      "Medium",
      "Close-up",
      "Extreme Close-up",
      "Full Body",
      "Portrait",
      "Establishing Shot"
    ]
  },
  subject: {
    characteristic: [
      "Young",
      "Old",
      "Athletic",
      "Slim",
      "Muscular",
      "Elegant",
      "Casual",
      "Professional",
      "Adventurous",
      "Mysterious"
    ],
    clothes: [
      "Formal",
      "Casual",
      "Traditional",
      "Futuristic",
      "Fantasy",
      "Business",
      "Athletic",
      "Vintage",
      "Streetwear",
      "None"
    ],
    action: [
      "Standing",
      "Sitting",
      "Walking",
      "Running",
      "Dancing",
      "Fighting",
      "Reading",
      "Working",
      "Relaxing",
      "Sleeping",
      "Flying",
      "Swimming",
      "Driving",
      "Cooking",
      "Playing Instrument",
      "Singing",
      "Interacting"
    ],
    top_type: [
      "T-shirt",
      "Shirt",
      "Blouse",
      "Crop top",
      "Tank top",
      "Sweater",
      "Hoodie",
      "Jacket",
      "Coat",
      "Robe",
      "Bra",
      "Bralette",
      "Bikini Top",
      "Sports Bra",
      "Corset",
      "Armor",
      "None"
    ],
    bottom_type: [
      "Jeans",
      "Pants",
      "Skirt",
      "Shorts",
      "Dress",
      "Leggings",
      "Panties",
      "Underwear",
      "Bikini Bottom",
      "Fishnet Stockings",
      "Armor",
      "None"
    ],
    accessories: [
      "Glasses",
      "Hat",
      "Scarf",
      "Jewelry",
      "Watch",
      "Gloves",
      "Belt",
      "Hand Bag",
      "Backpack",
      "Shoulder Bag",
      "Headphones",
      "Mask",
      "Veil",
      "Chains",
      "Choker",
      "Necklace",
      "Bracelet",
      "Ring",
      "Earrings",
      "None"
    ],
    weapon: [
      "Sword",
      "Katana",
      "Axe",
      "Gun",
      "Bow",
      "Crossbow",
      "Staff",
      "Dagger",
      "Spear",
      "Hammer",
      "Magic wand",
      "Nunchucks",
      "Bo Staff",
      "Glaive",
      "Flail",
      "None"
    ]
  },
  scene: {
    scene_1: [
      "Indoor",
      "Bedroom",
      "Living Room",
      "Kitchen",
      "Bathroom",
      "Studio",
      "Office",
      "Outdoor",
      "Beach",
      "Desert",
      "Forest",
      "Mountain",
      "City",
      "Urban",
      "Nature",
      "Fantasy World",
      "Cyberpunk",
      "Historical",
      "Sci-Fi",
      "Post-Apocalyptic",
      "Underwater",
      "Space"
    ],
    scene_2: [
      "Day",
      "Night",
      "Dusk",
      "Sunset",
      "Sunrise",
      "Overcast",
      "Rainy",
      "Snowy",
      "Foggy",
      "Stormy"
    ]
  },
  lighting: {
    lighting_1: [
      "Natural",
      "Studio",
      "Golden Hour",
      "Blue Hour",
      "Night City Lights",
      "Neon",
      "Cinematic",
      "Soft",
      "Hard",
      "Backlit",
      "Rembrandt",
      "Butterfly"
    ],
    lighting_2: [
      "Front Lit",
      "Back Lit",
      "Side Lit",
      "Rim Light",
      "Dramatic",
      "Flat",
      "High Contrast",
      "Low Key",
      "High Key",
      "Cinematic",
      "Film Noir",
      "Silhouette"
    ]
  }
};
